<a href="https://colab.research.google.com/github/lokeshneerasa/Numpyyy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **#############NUMPY###############**

In [ ]:
# NUMPY-FUNDAMENTALS
#1. Creating numpy array
#2. numpy.ndim
#3. Indexing and Slicing
#4. Creating a array with all zeros
#5. Creating a array with all ones

##1.NUMPY.NDIM
import numpy as np
a=50
b=np.array(a)           #Zero Dimension
print(b)
print(type(b))
print(b.ndim)
print("------------------------------------------------------------------------------------")

import numpy as np
a=[10,20,30,40,50]     #One Dimension
b=np.array(a)
print(b)
print(type(b))
print(b.ndim)
print("------------------------------------------------------------------------------------")

import numpy as np
a=[10,20,30],[40,50,60]   #Two Dimension
b=np.array(a)
print(b)
print(type(b))
print(b.ndim)
print("------------------------------------------------------------------------------------")

import numpy as np
a=[10,20,30],[40,50,60],[70,80,90]
b=np.array(a)
print(b)
print(type(b))
print(b.ndim)
print("------------------------------------------------------------------------------------")


##2.INDEXING AND SLICING ##
import numpy as np
a=[10,20,30,40,50]              #By Using Index Number
b=np.array(a)
print(b)
print(b[0])
print(b[1])
print(b[2])
print("------------------------------------------------------------------------------------")

import numpy as np
a=[10,20,30,40,50,60]
b=np.array(a)
print(b)                       #By Using Range
print(b[3:])
print(b[1:4])
print("------------------------------------------------------------------------------------")

import numpy as np
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
b=np.array(a)

print(b[0,0])
print(b[0,1])                 #By Using Matrix
print(b[0,2])

print(b[1,0])
print(b[1,1])
print(b[1,2])

print(b[2,0])
print(b[2,1])
print(b[2,2])
print("------------------------------------------------------------------------------------")

### Index Error
# import numpy as np
# a=[10,20,30,40,50,60]
# b=np.array(a)
# print(b)
# print(b[37])
#print("------------------------------------------------------------------------------------")


## 3.Creating Array with All Zeros
import numpy as np
a=np.zeros(6)
print(a)
print("------------------------------------------------------------------------------------")

import numpy as np
a=np.zeros((2,8))
print(a)
print("------------------------------------------------------------------------------------")

## 4.creating Array with All Ones
import numpy as np
a=np.ones(7)
print(a)
print("------------------------------------------------------------------------------------")

import numpy as np
a=np.ones((2,9))
print(a)
print("------------------------------------------------------------------------------------")

import numpy as np
a=[2,3]
b=np.zeros(a,int)
print(b)
print("------------------------------------------------------------------------------------")

import numpy as np
a=[4,5]
b=np.ones(a,int)
print(b)
print("------------------------------------------------------------------------------------")







50
<class 'numpy.ndarray'>
0
------------------------------------------------------------------------------------
[10 20 30 40 50]
<class 'numpy.ndarray'>
1
------------------------------------------------------------------------------------
[[10 20 30]
 [40 50 60]]
<class 'numpy.ndarray'>
2
------------------------------------------------------------------------------------
[[10 20 30]
 [40 50 60]
 [70 80 90]]
<class 'numpy.ndarray'>
2
------------------------------------------------------------------------------------
[10 20 30 40 50]
10
20
30
------------------------------------------------------------------------------------
[10 20 30 40 50 60]
[40 50 60]
[20 30 40]
------------------------------------------------------------------------------------
10
20
30
40
50
60
70
80
90
------------------------------------------------------------------------------------
[0. 0. 0. 0. 0. 0.]
------------------------------------------------------------------------------------
[[0. 0. 0. 0. 0. 0.

In [ ]:
## NUMPY-ATTRIBUTE
# 1.Numpy Array Attributes
# 2.shape attribute
# 3.ndim attribute
# 4.arrayobject

##Shape Attribute
import numpy as np
a=np.array([10,20,30,40,50])
b=np.array(a)
print(b)
print(b.shape)
print("------------------------------------------------------------------------------------")

import numpy as np
a=np.array([[10,20,30],[40,50,60]])
b=np.array(a)
print(b)
print(b.shape)
print("------------------------------------------------------------------------------------")

##NDIM Attribute
import numpy as np
a=np.array([[10,20,30],[40,50,60]])
b=np.array(a)
print(b)
print(type(b))
print(b.ndim)
print("------------------------------------------------------------------------------------")

##Array Object.T
import numpy as np
a=np.array([[10,20,30],[40,50,60]])
b=np.array(b)
print(b)
print(b.T)



[10 20 30 40 50]
(5,)
------------------------------------------------------------------------------------
[[10 20 30]
 [40 50 60]]
(2, 3)
------------------------------------------------------------------------------------
[[10 20 30]
 [40 50 60]]
<class 'numpy.ndarray'>
2
------------------------------------------------------------------------------------
[[10 20 30]
 [40 50 60]]
[[10 40]
 [20 50]
 [30 60]]


In [ ]:
##NUMPY-IMPORTANT METHODS
# 1. Numpy Array Methods
# 2. min() method
# 3. max() method
# 4. sum() method
# 5. reshape() method
# 6. count_nonzero(p) function
# 7. sort() method
# 8. flatten() method
# 9. adding value to array of values
# 10. Diagonal of a Matrix
# 11. Trace of a Matrix
# 12. Adding and Subtracting Matrices

#Min()Method
import numpy as np
a=np.array([10,20,30,40,50,60])
b=np.array(a)
print(b)
print(b.min())
print("----------------------------------------------------------")

#Max()Method
import numpy as np
a=np.array([10,20,30,40,50,60])
b=np.array(a)
print(b)
print(b.max())
print("----------------------------------------------------------")

#Sum Method()
import numpy as np
a=([10,20,30],[40,50,60])
b=np.array(a)
print(b)
print(b.sum())
print("----------------------------------------------------------")

#Reshape Method()
import numpy as np
a=([10,20,30],[40,50,60])
b=np.array(a)
print(b)
print()
print(b.reshape(6,1))
print("----------------------------------------------------------")

import numpy as np
details = [10, 20, 30, 40, 50, 60, 10, 20, 10, 10, 20, 10, 10, 20, 30, 40, 50, 60, 10, 20, 10, 10, 20, 10]
sales = np.array(details)
# reshape into 3D array → shape (3, 2, 4)
sales = np.reshape(sales, (3, 2, 4))
print(sales)
print(type(sales))
print(sales.ndim)
print("----------------------------------------------------------")

#count_nonzero(p) function
import numpy as np
a=([10,0,30],[0,50,60])
b=np.array(a)
print(b)
print()
print(np.count_nonzero(b))
print("----------------------------------------------------------")

#Sort Method()
import numpy as np
a=([60,10,70],[40,90,30])
b=np.array(a)
print(b)
print()
print(np.sort(b))
print("----------------------------------------------------------")

#flatten() method
import numpy as np
a=([10,20,30],[40,50,60])
b=np.array(a)
print(b)
print()
print(b.flatten())
print("----------------------------------------------------------")

#adding value to array of values
import numpy as np
a=([10,20,30],[40,50,60])
b=np.array(a)
print(b)
print()
print(b+5)
print("----------------------------------------------------------")

#Diagonal of a Matrix
import numpy as np
a=([10,20,30],[40,50,60],[70,80,90])
b=np.array(a)
print(b)
print()
print(b.diagonal())
print("----------------------------------------------------------")

#Trace of a Matrix
import numpy as np
a=([10,20,30],[40,50,60],[70,80,90])
b=np.array(a)
print(b)
print()
print(b.trace())
print("----------------------------------------------------------")

# Adding and Subtracting Matrices

#Adding
import numpy as np
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
b=np.array([[30,40,50],[60,70,80],[10,20,40]])
print(a)
print()
print(b)
print()
print(np.add(a,b))
print("----------------------------------------------------------")

#Subtraction
import numpy as np
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
b=np.array([[30,40,50],[60,70,80],[10,20,40]])
print(a)
print()
print(b)
print()
print(np.subtract(a,b))
print("----------------------------------------------------------")




















[10 20 30 40 50 60]
10
----------------------------------------------------------
[10 20 30 40 50 60]
60
----------------------------------------------------------
[[10 20 30]
 [40 50 60]]
210
----------------------------------------------------------
[[10 20 30]
 [40 50 60]]

[[10]
 [20]
 [30]
 [40]
 [50]
 [60]]
----------------------------------------------------------
[[[10 20 30 40]
  [50 60 10 20]]

 [[10 10 20 10]
  [10 20 30 40]]

 [[50 60 10 20]
  [10 10 20 10]]]
<class 'numpy.ndarray'>
3
----------------------------------------------------------
[[10  0 30]
 [ 0 50 60]]

4
----------------------------------------------------------
[[60 10 70]
 [40 90 30]]

[[10 60 70]
 [30 40 90]]
----------------------------------------------------------
[[10 20 30]
 [40 50 60]]

[10 20 30 40 50 60]
----------------------------------------------------------
[[10 20 30]
 [40 50 60]]

[[15 25 35]
 [45 55 65]]
----------------------------------------------------------
[[10 20 30]
 [40 50 60]
 [7